name: BDD Firefox
on:
  #push:
    #branches: [master]
  pull_request:
    branches: [master]
  #repository_dispatch:
    #types: [qa]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      firefox:
        image: selenium/node-firefox:3.141.59-gold
        env:
          HUB_HOST: hub
          HUB_PORT: 4444
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Checkout openelis qaframework
        uses: actions/checkout@master
        with:
          repository: ${{github.repository}}
      - name: Run qaframework on selenium
        run: |
          echo "cucumber.publish.enabled=true" > src/test/resources/cucumber.properties
          mvn clean install -Dcucumber.filter.tags='@null' 
          mvn test
          curl -sX POST -F messages=@target/cucumber.ndjson https://studio.cucumber.io/cucumber_project/results -H "project-access-token: ${{secrets.CUCUMBER_IO_TOKEN}}" -H "provider: github" -H "repo: ${{github.repository}}" -H "branch: master" -H "revision: ${{github.sha}}"
