name: OpenELIS QA
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest         
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Checkout openelis qaframework
        uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}
      - name:  Start the Remote web driver in docker  
        run:  |
              docker-compose up chrome -d
      - name: Sleep for 3 minutes 
        run: sleep 3m
        shell: bash     
      - name: Run and Publish Openelis QA
        run: |
          echo "cucumber.publish.enabled=true" > src/test/resources/cucumber.properties
          mvn clean install -DskipTests=true 
          mvn test   
          curl -X POST \
          https://studio.cucumber.io/cucumber_project/results \
          -F messages=@./target/cucumber.ndjson  \
          -H "project-access-token: ${{secrets.CUCUMBER_IO_TOKEN}}" \
          -H "provider: github" \
          -H "repo: ${{github.repository}}" \
          -H "branch: main" \
          -H "revision: ${{github.sha}}"