name: Referral Work Flow  Feature
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest         
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Checkout openelis qaframework
        uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}
      - name:  Start the Remote web driver in docker  
        run:  |
              docker-compose up -d chrome
      - name: Sleep for 3 minutes 
        run: sleep 3m
        shell: bash      
      - name: Run and Publish Openelis QA
        run: |
          mvn clean install -DskipTests=true 
          mvn test -Dcucumber.filter.tags='@referral'    
