name: CI-LOCAL TEST
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest         
    steps:
      - name: Checkout OpenELIS Global
        uses: actions/checkout@v2
        with:
          repository: I-TECH-UW/OpenELIS-Global-2
          ref: CI
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}    
      - name:  Spin UP OpenELIS server 
        run:  |
              docker-compose up -d
      - name: Sleep for 10 minutes 
        run: sleep 10m
        shell: bash 
      - name: Check containers
        run: docker ps  
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Checkout openelis qaframework
        uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}
      - name: Run and Publish Openelis QA
        run: |
          echo "cucumber.publish.enabled=true" > src/test/resources/cucumber.properties
          mvn clean install -DskipTests=true 
          cp -f src/test/resources/test-local.properties src/test/resources/test.properties
          mvn test -Dcucumber.filter.tags='@login' 
          mvn test -Dcucumber.filter.tags='@order'    
          
